name: photo_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^3.0.0-dev.3
  http: ^1.2.1
  json_annotation: ^4.9.0
  mocktail: ^1.0.4
  riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4

dev_dependencies:
  build_runner: ^2.4.9


  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0


icons_launcher:
  image_path: "assets/images/icon.png"
  adaptive_background_color: '#F7F7F7'
  platforms:
    android:
      enable: true
    ios:
      enable: true


flutter_native_splash:
 
  color: "#ffffff"

  background_image: assets/images/icon.png
  
  android_12:
   
    color: "#ffffff"
    
  
    background_image: assets/images/icon.png

   

  android_gravity: center
 
flutter:


  uses-material-design: true

  assets:
    - assets/images/
  